services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_HOST_AUTH_METHOD: md5
  #     POSTGRES_INITDB_ARGS: "--auth=md5 -c log_statement=all"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 500mb
  #         cpus: '0.25'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    deploy:
      resources:
        limits:
          memory: 500mb
          cpus: '0.25'

  # pgbouncer:
  #   image: edoburu/pgbouncer
  #   environment:
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_HOST=db
  #     - MAX_CLIENT_CONN=100000
  #     # - DB_NAME=test
  #     - POOL_MODE=transaction
  #     - ADMIN_USERS=postgres,dbuser
  #   ports:
  #     - "5432:5432"
  #   depends_on:
  #     - db
    
  bank:
    image: bank
    # ports:
    #   - 8086:8080
    build:
      context: .
      dockerfile: src/Bank/Dockerfile
    # environment:
      # - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      mode: replicated
      replicas: 5
      endpoint_mode: vip
    depends_on:
      - rabbitmq
    
      # resources:
      #   limits:
      #     memory: 500m
      #     cpus: '0.25'


  # bank:
  #   image: bankorleans
  #   build:
  #     context: .
  #     dockerfile: src/bankOrleans/Dockerfile
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     endpoint_mode: vip
  #   # environment:
  #   #   - ASPNETCORE_ENVIRONMENT=Development

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bank
    ports:
      - 8081:8080